# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665b14c19788a1d37f8f86752ebb33b1a9af84099865851258bd17ba3fff00a854a38d0ef22d8d5cd7ea70531adc14aa92e67307aee9b806c84aa9ed70b044d9

test:
  secret_key_base: ddefd6ce0396f2895e379e47d42b81b72d3fdc3afc95e9d1574aa7219690ba1865131d52c927b3cce85764237cb9e72a7eca9d7c88f9a39d4560cbb030792fa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
